// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM2n_KnRRyIvQyULH9hMgxXLrUKUVfqm4',
    appId: '1:457489517146:web:816fef424f7e7b7bbd2663',
    messagingSenderId: '457489517146',
    projectId: 'memotask-trabmobile',
    authDomain: 'memotask-trabmobile.firebaseapp.com',
    storageBucket: 'memotask-trabmobile.appspot.com',
    measurementId: 'G-86E03BF89D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCETY09nvUyRJVCxDU1z_IGHWo4IXtLtEY',
    appId: '1:457489517146:android:fbc22f6672b21677bd2663',
    messagingSenderId: '457489517146',
    projectId: 'memotask-trabmobile',
    storageBucket: 'memotask-trabmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3XhFiyg1YiurjBRqrP0Ska3IwamGy6oQ',
    appId: '1:457489517146:ios:8fa5092bb1859f65bd2663',
    messagingSenderId: '457489517146',
    projectId: 'memotask-trabmobile',
    storageBucket: 'memotask-trabmobile.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3XhFiyg1YiurjBRqrP0Ska3IwamGy6oQ',
    appId: '1:457489517146:ios:8fa5092bb1859f65bd2663',
    messagingSenderId: '457489517146',
    projectId: 'memotask-trabmobile',
    storageBucket: 'memotask-trabmobile.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
